# This is a basic workflow to help you get started with Actions

name: Star validation

# Controls when the workflow will run
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  schedule:
    - cron: "5 * * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow checks if a user has starred a repository and takes actions
  starcheck:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          message: "Please star this repository to motivate developers! :star:"
